# Generated by Django 2.2.16 on 2020-11-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0019_userstory_from_task_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='set_in_progress_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='set in progress time'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='time_spent_to_date',
            field=models.IntegerField(default=0, verbose_name='time spent'),
        ),
    ]
