# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-07 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_due_date'),
        ('issues', '0008_add_due_date'),
    ]

    operations = [
    ]
