# Generated by Django 2.2.16 on 2020-11-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_auto_20200615_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='set_in_progress_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='set in progress time'),
        ),
        migrations.AddField(
            model_name='issue',
            name='time_spent_to_date',
            field=models.IntegerField(default=0, verbose_name='time spent'),
        ),
    ]
